### ISSUE TITLE
Erro when trying to run Bigwarp from Plugins > BigDataViewer > Bigwarp XML/HDF5

### ISSUE THREAD

**Issue by bpavie** [saalfeldlab/bigwarp#104] opened 2020-09-17 16:44 UTC
Dear,

I tried to open BigWarp from HDF5 files generated using  `Plugins > BigDataViewer > Export Current Image as XML/HDF5`
The conversion worked fine and I can open and see the 2 images with the BigDataViewer.

I then next tried to open BigWarp using  `Plugins > BigDataViewer > Bigwarp XML/HDF5` and point to the XML files but encounter this error:

```
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 9174MB of 24353MB (37%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at bigwarp.BigWarp$BigWarpData.transferChannelSettings(BigWarp.java:2813)
	at bigwarp.BigWarp.<init>(BigWarp.java:544)
	at bigwarp.BigWarp.<init>(BigWarp.java:317)
	at bdv.ij.BigWarpBdvCommand.run(BigWarpBdvCommand.java:44)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

If I point to the h5 files instead of the XML files, I don't have the error but nothing show up (and nothing happends I think).
The generated macro is :
`IJ.run("Big Warp XML/HDF5", "fixedimagexml=C:\\test\\export_01.h5 movingimagexml=C:\\test\\export_02.h5");`

Version:
bigdataviewer_fiji-6.2.0.jar
bigwarp_fiji-6.0.0.jar
ImageJ:1.53c
OS: Windows 10

The dataset is 2 multichannels images with only one plane (2D)

Would you have any tips?

Benjamin

**Comment by bogovicj** [comment] 2020-09-17 17:22
Thanks for reporting.

**Comment by bpavie** [comment] 2020-09-21 13:51
Actually, it works with the bigwarp_fiji-6.0.2.jar that I found in https://biop.epfl.ch/Fiji-Bdv-Playground/plugins/ so we just need to have the update from Fiji update I guess (or compile it)

**Comment by bogovicj** [comment] 2020-09-22 16:09
Good to hear.
Since the issue isn't present in new code, I'm closing this issue.

**Closed by bogovicj** 2020-09-22 16:09 UTC
